Flex({ direction: FlexDirection.Column }) {
  Text('Replace Flex with Column/Row')
    .fontSize(12)
    .height('16')
    .margin({
      top: 5,
      bottom: 10
    })
  Flex().width(300).height(200).backgroundColor(Color.Pink)
  Flex().width(300).height(200).backgroundColor(Color.Yellow)
  Flex().width(300).height(200).backgroundColor(Color.Grey)
  Flex().width(300).height(200).backgroundColor(Color.Pink)
  Flex().width(300).height(200).backgroundColor(Color.Yellow)
  Flex().width(300).height(200).backgroundColor(Color.Grey)
}.height(200)